# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ip_event.proto", :syntax => :proto2) do
    add_message "definitions.IpEvent" do
      required :app_sha256, :string, 1
      required :ip, :int64, 2
    end
  end
end

module Definitions
  IpEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("definitions.IpEvent").msgclass
end
